### ISSUE TITLE
Repeated Nodes

### ISSUE THREAD

**Issue by codykingham** [biblicalhumanities/greek-new-testament#13]
Acts contains a duplicate set of nodes:

See nodeId's 440150290150010-440150290150012

**Comment by jonathanrobie** [comment]
Thanks!  This looks like a clear bug - even the nodeIDs are duplicated!

**Comment by rkjtan** [comment]
This is a problem with how the automatic parser treats this kind of situation with only one word on its own in this kind of exact situation, which left 2 alternate trees. The tree that never promotes to a CL is the undesired one that should be discarded.

**Comment by jonathanrobie** [comment]
It's easy enough for me to remove the duplicate nodes manually - is that
the best approach?

**Comment by jonathanrobie** [comment]
Fixed in Acts, but there are three other places with duplicate nodes:

2Tm4:1:1-4:1:21
Jms2:18:10-2:18:26
Jms2:20:1-2:20:14

Each one has two distinct trees. Randall, which one should be deleted in each case?

I wrote this query to check for duplicate nodes in trees:

for $n in //*[@nodeId]
let $id := $n/@nodeId
group by $id
order by $id
where count($n) > 1
return $n/@nodeId

All of the duplicate nodes were due to multiple Tree elements under Trees, which can easily be found using this query:

//Trees[count(Tree) > 1]

**Comment by rkjtan** [comment]
These 3 places are remnants of an experiment in allowing multiple trees that GBI has temporarily abandoned.

2Tm4:1:1-4:1:21 Delete the 2nd tree that has V-ADV-O
Jms2:18:10-2:18:26 Delete the 2nd tree that has V-IO-O for the 1st clause
Jms2:20:1-2:20:14 Delete the 2nd tree that has S-P-VC for the HOTI (last) clause

**Comment by jonathanrobie** [comment]
I have committed these changes for the full-fat trees.
